# Generated by Django 3.2.12 on 2024-06-05 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_auto_20240605_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='base_salary',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='deductions',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='emp_app.employee'),
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('benefits', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('emp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary', to='emp_app.employee')),
            ],
        ),
    ]
