# Generated by Django 5.0.6 on 2024-06-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0005_attendance_days_present_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='days_present',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='days_present',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('not marked', 'Not Marked'), ('present', 'Present'), ('absent', 'Absent'), ('half day', 'Half Day'), ('leave', 'Leave')], default='Not Marked', max_length=10),
        ),
    ]
